# Swaybar configuration
bar {
	position bottom
	status_command i3status c ~/.config/i3status/config
	
	font pango:terminus
	workspace_buttons yes
	strip_workspace_numbers yes

	colors {
		background #2b2b2b
		statusline #ffffff
		separator #333333

		focused_workspace #4c7899 #4c7899 #ffffff
		active_workspace #333333 #333333 #ffffff
		inactive_workspace #2b2b2b #2b2b2b #888888
		active_workspace #eb5656 #eb5656 #ffffff
	}
}
		
		
